# Generated by Django 3.1.5 on 2021-06-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(default='', max_length=60)),
                ('state', models.CharField(default='', max_length=30)),
                ('zipcode', models.CharField(default='', max_length=5)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('package_location', models.CharField(max_length=255)),
                ('package_destination', models.CharField(max_length=255)),
                ('package_worth', models.IntegerField(default=0)),
                ('package_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_weight', models.CharField(max_length=30)),
                ('package_brand', models.CharField(max_length=30)),
                ('package_SKU', models.CharField(max_length=60)),
                ('package_width', models.CharField(max_length=255)),
                ('package_color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bio', models.TextField(verbose_name=60)),
                ('earnings', models.IntegerField(default=0.0)),
                ('rating', models.IntegerField(default=0)),
                ('address', models.ManyToManyField(to='core.Address')),
                ('rewards', models.ManyToManyField(to='core.Rewards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
