# Generated by Django 2.2.3 on 2020-02-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_color',
        ),
        migrations.AlterField(
            model_name='package',
            name='delivered_on',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.ManyToManyField(blank=True, to='core.Document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='user_images'),
        ),
    ]
