# Generated by Django 2.2.3 on 2020-02-24 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200224_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivered_on',
            field=models.DateTimeField(blank=True, default='', verbose_name=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
