# Generated by Django 3.1.5 on 2021-06-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210610_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_image',
            field=models.ImageField(default='item_avatar.jpg', upload_to='package_pics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='favicon.jpg', upload_to='profile_pics'),
        ),
    ]
