# Generated by Django 2.2.3 on 2020-02-24 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200224_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='delivered_on',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime),
        ),
    ]
